import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { verifyPasswordProof } from '../src/login-proof.js';
const auth=fs.readFileSync('src/auth.js','utf8');
const worker=fs.readFileSync('src/worker.js','utf8');
const ui=fs.readFileSync('src/ui.js','utf8');
const helper=fs.readFileSync('src/login-proof.js','utf8');
assert.match(auth,/login_required/);
assert.match(auth,/__Host-csf/);
assert.match(auth,/loginRequired===false/);
assert.match(auth,/auth_challenges/);
assert.match(auth,/DELETE FROM auth_challenges/);
assert.match(ui,/PBKDF2/);
assert.match(ui,/passwordProof/);
assert.match(helper,/crypto\.subtle\.verify/);
assert.match(worker,/getSession\(request,env\)/);
assert.match(worker,/if\(!owner&&\(required/);
assert.match(worker,/scopeSql/);
assert.match(worker,/numopede_checks/);
assert.match(worker,/audit_reviews/);
assert.match(auth,/SELECT u.username,u.role,u.companies,u.lawyers/);
assert.match(auth,/api\/auth\/users/);
assert.match(ui,/api\/ranking/);
assert.match(ui,/api\/numopede/);
assert.doesNotMatch(worker,/Cf-Access-Jwt-Assertion/);
assert.doesNotMatch(auth,/Eufalhei/);
const key=Buffer.alloc(32,0x61);
const nonce='test-nonce',id='test-id',username='Auditoria';
const proof=createHmac('sha256',key).update(['csf-login-v1',nonce,id,username.toLowerCase()].join(':')).digest('base64url');
assert.equal(await verifyPasswordProof(key.toString('base64url'),nonce,id,username,proof),true);
assert.equal(await verifyPasswordProof(key.toString('base64url'),nonce,id,username,'invalid-proof'),false);
assert.equal(await verifyPasswordProof(key.toString('base64url'),nonce,id,'Other',proof),false);
console.log('PASS: login challenge/proof, one-use challenge, sessions and public summary protections.');
