import fs from 'node:fs';
import assert from 'node:assert/strict';
const auth=fs.readFileSync('src/auth.js','utf8');
const worker=fs.readFileSync('src/worker.js','utf8');
const ui=fs.readFileSync('src/ui.js','utf8');
const page=fs.readFileSync('src/page.js','utf8');
assert.match(auth,/PBKDF2/);
assert.match(auth,/login_required/);
assert.match(auth,/__Host-csf/);
assert.match(auth,/loginRequired===false/);
assert.match(auth,/EXIBIR APENAS DADOS ANONIMIZADOS/);
assert.doesNotMatch(auth,/Eufalhei/);
assert.match(worker,/getSession\(request,env\)/);
assert.match(worker,/if\(!owner\)return send/);
assert.doesNotMatch(worker,/Cf-Access-Jwt-Assertion/);
assert.match(ui,/submitLogin/);
assert.match(ui,/saveSettings/);
assert.match(page,/UI_JS/);
console.log('OK: login próprio, ON/OFF e proteção das rotas privadas presentes.');
